### ISSUE TITLE
--connection param isnt working?

### ISSUE THREAD

**Issue by shez1983** [stefanzweifel/laravel-backup-restore#23] opened 2023-08-22 14:18 UTC
so i have two db configs keys one is mysql, one is restore-db.  i am using spatie to do a backup of mysql and then using this package to db defined in restore-db key.

when i run this command LOCALLY it SEEMS to be working fine. 

``` artisan backup:restore --disk=s3 --backup=latest --no-interaction --connection=restore-db```

but on staging what it is doing is IGNORING restore-db, and restoring to db defined in mysql..

**Comment by stefanzweifel** [comment] 2023-08-22 17:53
Have to do some digging here. Maybe that's related to #22 and we somehow mix up connection and driver.

**Comment by stefanzweifel** [comment] 2023-08-22 18:20
I'm not able to reproduce this issue.

In #20 we've updated the command to show the exact connection information in the confirmation dialog.
We have [tests](https://github.com/stefanzweifel/laravel-backup-restore/blob/a836fb3a04cf020a6fb25199d1ea7353b4926f20/tests/Commands/RestoreCommandTest.php#L20) that assert that the right connection is used and shown to the user.

By using `--no-interaction` Laravel/the command doesn't ask for confirmation and just proceeds with restoring the backup. Could you share the output you receive when running the command without `---no-interaction`?

```shell
php artisan backup:restore --disk=s3 --backup=latest --connection=restore-db
```

**Comment by stefanzweifel** [comment] 2023-10-24 17:33
Closing this issue as I'm not able to reproduce this issue.
Feel free to add a comment with more details if you still encounter this issue.

**Closed by stefanzweifel** 2023-10-24 17:33 UTC
Labels: bug
